### ISSUE TITLE
Publish date for version 0.2.0

### ISSUE THREAD

**Issue by xiaoli9235** [rusticata/ssh-parser#2]
Hi, I've noticed that the latest version on crate.io is 0.1.3, which depends on `nom ^3.1.0`. But it looks like you've updated all the necessary dependencies in version 0.2.0 so I'm wondering when do you plan to publish 0.2.0? Thanks in advance.

**Comment by chifflier** [comment]
Hi,
I uploaded 0.2.0 to crates.io, so closing this issue.
